version: '3.9'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - data-volume:/var/lib/mysql
    ports:
      - 3306:3306

  api:
    build: ./api
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - ./api:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  front:
    build: ./front
    command: npm run dev
    volumes:
      - ./front:/app
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
  data-volume:
